/*
 Navicat Premium Data Transfer

 Source Server         : 淖毛湖
 Source Server Type    : MySQL
 Source Server Version : 80023 (8.0.23)
 Source Host           : 172.20.1.42:3306
 Source Schema         : web-test

 Target Server Type    : MySQL
 Target Server Version : 80023 (8.0.23)
 File Encoding         : 65001

 Date: 24/07/2024 17:12:27
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for ROLE_PERMISSION
-- ----------------------------
DROP TABLE IF EXISTS `ROLE_PERMISSION`;
CREATE TABLE `ROLE_PERMISSION`  (
  `ID` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `ROLE_ID` bigint NOT NULL COMMENT '角色ID',
  `PERMISSION_ID` bigint NOT NULL COMMENT '权限ID',
  `IS_DELETED` tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否删除',
  `UNIQUE_LOCK` bigint NOT NULL DEFAULT 0 COMMENT '唯一性锁',
  `REVISION` int NULL DEFAULT 1 COMMENT '乐观锁',
  `CREATED_BY` bigint NULL DEFAULT NULL COMMENT '创建人',
  `CREATED_TIME` datetime NULL DEFAULT NULL COMMENT '创建时间',
  `UPDATED_BY` bigint NULL DEFAULT NULL COMMENT '更新人',
  `UPDATED_TIME` datetime NULL DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`ID`) USING BTREE,
  UNIQUE INDEX `UNIQUE_ROLE_ID_PERMISSION_ID_UNIQUE_LOCK`(`ROLE_ID` ASC, `PERMISSION_ID` ASC, `UNIQUE_LOCK` ASC) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 16 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci COMMENT = '角色权限表' ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of ROLE_PERMISSION
-- ----------------------------
INSERT INTO `ROLE_PERMISSION` VALUES (1, 1, 1, 0, 0, 1, NULL, NULL, NULL, NULL);
INSERT INTO `ROLE_PERMISSION` VALUES (2, 1, 2, 0, 0, 1, NULL, NULL, NULL, NULL);
INSERT INTO `ROLE_PERMISSION` VALUES (3, 1, 3, 0, 0, 1, NULL, NULL, NULL, NULL);
INSERT INTO `ROLE_PERMISSION` VALUES (4, 1, 5, 0, 0, 1, NULL, NULL, NULL, NULL);
INSERT INTO `ROLE_PERMISSION` VALUES (5, 1, 6, 0, 0, 1, NULL, NULL, NULL, NULL);
INSERT INTO `ROLE_PERMISSION` VALUES (6, 1, 7, 0, 0, 1, NULL, NULL, NULL, NULL);
INSERT INTO `ROLE_PERMISSION` VALUES (7, 1, 8, 0, 0, 1, NULL, NULL, NULL, NULL);
INSERT INTO `ROLE_PERMISSION` VALUES (8, 1, 9, 0, 0, 1, NULL, NULL, NULL, NULL);
INSERT INTO `ROLE_PERMISSION` VALUES (9, 1, 10, 0, 0, 1, NULL, NULL, NULL, NULL);
INSERT INTO `ROLE_PERMISSION` VALUES (10, 1, 11, 0, 0, 1, NULL, NULL, NULL, NULL);
INSERT INTO `ROLE_PERMISSION` VALUES (11, 1, 12, 0, 0, 1, NULL, NULL, NULL, NULL);
INSERT INTO `ROLE_PERMISSION` VALUES (12, 1, 13, 0, 0, 1, NULL, NULL, NULL, NULL);
INSERT INTO `ROLE_PERMISSION` VALUES (13, 1, 14, 0, 0, 1, NULL, NULL, NULL, NULL);
INSERT INTO `ROLE_PERMISSION` VALUES (14, 1, 15, 0, 0, 1, NULL, NULL, NULL, NULL);
INSERT INTO `ROLE_PERMISSION` VALUES (15, 1, 16, 0, 0, 1, NULL, NULL, NULL, NULL);

SET FOREIGN_KEY_CHECKS = 1;
